name: AWS-Flow
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCT_ID }}:role/GHIAMRole
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: init and plan terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: init terraform
        working-directory: Terraform/TerraformLocalCloud
        run: terraform init
      
      - name: Plan Terraform
        working-directory: Terraform/TerraformLocalCloud 
        id: plan
        run: terraform plan -no-color

