name: Workflow1
on:
  workflow_dispatch:
    inputs:
          terraformaction:
            type: choice
            description: Terraform Action
            options: 
            - Plan
            - Apply
            - Destroy
            - Import
permissions:
  id-token: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCT_ID }}:role/TerraformInActionIAMRole
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: pwd
      #   shell: bash
      #   run: |
      #     pwd
      #     ls

      - name: init and plan terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: init terraform
        working-directory: TF
        run: terraform init
      
      - name: Plan Terraform
        if: ${{ github.event.inputs.terraformaction== 'Plan' }}
        working-directory: TF
        id: plan
        run: terraform plan -no-color

      - name: Apply Terraform
        if: ${{ github.event.inputs.terraformaction== 'Apply' }}
        working-directory: TF
        id: apply
        run: terraform apply -no-color -auto-approve

      - name: Destroy Terraform
        if: ${{ github.event.inputs.terraformaction== 'Destroy' }}
        working-directory: TF
        id: destroy
        run: terraform destroy -no-color -auto-approve